# 1. Bancos de Dados Relacionais
databases:
  - name: atlas-database
    plan: free

# 2. Serviços da Aplicação (Web Services)
services:
  # Servidor Backend (NestJS API)
  - type: web
    name: atlas-api
    plan: free
    runtime: node
    buildCommand: pnpm install && pnpm --filter @atlas/api prisma:generate && pnpm build
    startCommand: pnpm --filter @atlas/api start
    envVars:
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: atlas-database
          property: connectionString
      - key: JWT_SECRET
        generateValue: true # Gera um secret seguro aleatório de forma automática
      - key: FRONTEND_URL
        value: https://atlas-web.onrender.com
      # Chaves de APIs externas do UploadThing e Resend
      - key: UPLOADTHING_TOKEN
        sync: false
      - key: RESEND_API_KEY
        sync: false

  # Frontend (Next.js Web App)
  - type: web
    name: atlas-web
    plan: free
    runtime: node
    buildCommand: pnpm install && pnpm build
    startCommand: pnpm --filter @atlas/web start
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://atlas-api.onrender.com
