export enum AuditAction {
  JOB_CREATED = "JOB_CREATED",
  JOB_UPDATED = "JOB_UPDATED",
  JOB_PUBLISHED = "JOB_PUBLISHED",
  JOB_CLOSED = "JOB_CLOSED",
  APPLICATION_RECEIVED = "APPLICATION_RECEIVED",
  CANDIDATE_STATUS_CHANGED = "CANDIDATE_STATUS_CHANGED",
  CANDIDATE_CONVERTED_TO_EMPLOYEE = "CANDIDATE_CONVERTED_TO_EMPLOYEE",
}
